# Site settings
title: 256 Foundation
email: admin@256foundation.org
url: https://256foundation.org
description: "A Free Open Source Bitcoin Mining, Energy, & Education Initiative."
keywords: "Bitcoin, Mining, Energy, Free, Open, Source"
skills: "<p>A Free Open Source Bitcoin Mining, Energy, & Education Initiative.</p><p>The 256 Foundation is a 501(c)(3) public charity, all donations are tax deductable.</p><h2>6.87 BTC Raised | $433k Allocated | 2-10m podcast subscribers</h2>"
meta_author: 256 Foundation

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 111111 #0a0a0a
  primary-rgb: "59,20,69" #"0,0,0"
  secondary: 3B1445 #1e4514-army-green #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: 256 Foundation
  location: Tennessee, USA
  social: Social
  faq: FAQ

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/256FOUNDATION
  - title: telegram
    url: https://t.me/the256foundation
 # - title: stack-overflow
 #   url: http://stackoverflow.com/questions/tagged/jekyll
  - title: feather
    url: https://primal.net/p/nprofile1qqsqhk42dz0exfcsln4yqmdkjys0nvd7dqndgacpsa7w7pt7njq2uuss2u9cq
  - title: github
    url: https://github.com/256-Foundation

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Credits content
faq: 'Find answers to common questions <a href="http://256foundation.org/faq.html" target="_blank" rel="noopener noreferrer"><font color="orange">here</font></a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
